backend:
  name: git-gateway
  repo: sethburtonhall/dks2.0
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }

  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - label: About
            name: about
            widget: object
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Intro, name: intro, widget: markdown }

      - label: "Clients"
        name: "clients"
        file: "content/pages/clients.md"
        fields:
          - label: Clients
            name: client
            widget: list
            fields:
              - { label: Client Name, name: clientName, widget: string }

      - label: "Testimonials"
        name: "testimonials"
        file: "content/pages/testimonials.md"
        fields:
          - label: Testimonials
            name: testimonial
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Company, name: company, widget: string }
              - { label: Quote, name: quote, widget: markdown }

      - label: "Contact"
        name: "contact"
        file: "content/pages/contact.md"
        fields:
          - label: Contact
            name: contact
            widget: object
            fields:
              - { label: Phone, name: phone, widget: string }
              - { label: Email, name: email, widget: string }

  - name: portfolio
    label: Portfolio
    folder: content/portfolio
    create: true
    fields:
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        media_folder: ""
        public_folder: ""
        media_library:
          config:
            multiple: false
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
